version: "3.4"

services:
  robber:
    image: es-domain-events/php:robber
    hostname: "robber"
    build:
      context: ./robber/php
    container_name: robber
    networks:
      - broker-kafka
    restart: on-failure
    volumes:
      - ./robber/app:/app
    env_file:
    - ./robber/dev.env
  house:
    image: es-domain-events/php:house
    hostname: "house"
    build:
      context: ./house/php
    networks:
      - broker-kafka
    container_name: house
    restart: on-failure
    volumes:
      - ./house/app:/app
    env_file:
    - ./house/dev.env
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    env_file:
    - dev.env

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    env_file:
    - dev.env

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    env_file:
    - dev.env

networks:
  broker-kafka:
    driver: bridge