version: "3.4"

services:
  world:
    image: es-domain-events/react:world
    hostname: "world"
    build:
      context: ./world
    container_name: world
    networks:
      - broker-kafka
    restart: unless-stopped
    volumes:
      - ./world:/app
    ports:
      - 3000:3000

  robber:
    image: es-domain-events/php:robber
    hostname: "robber"
    build:
      context: ./robber/docker
    container_name: robber
    networks:
      - broker-kafka
    restart: unless-stopped
    volumes:
      - ./robber/app:/app
    env_file:
      - ./robber/dev.env

  house:
    image: es-domain-events/php:house
    hostname: "house"
    build:
      context: ./house/docker
    networks:
      - broker-kafka
    container_name: house
    restart: unless-stopped
    volumes:
      - ./house/app:/app

  narrator:
    image: es-domain-events/php:narrator
    hostname: "narrator"
    build:
      context: ./narrator/docker
    networks:
      - broker-kafka
    container_name: narrator
    restart: unless-stopped
    volumes:
      - ./narrator/app:/app
    env_file:
      - ./narrator/dev.env
      
  hub:
    image: es-domain-events/php:hub
    hostname: "hub"
    build:
      context: ./hub/docker
    networks:
      - broker-kafka
    container_name: hub
    restart: unless-stopped
    volumes:
      - ./hub/app:/app
    env_file:
      - ./hub/dev.env
    ports:
      - 8083:8083

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: 'zookeeper'
    container_name: 'es-zookeeper'
    networks:
      - broker-kafka
    env_file:
      - dev.env

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: 'kafka'
    container_name: 'es-kafka'
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    env_file:
    - dev.env

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    env_file:
      - dev.env

  mysqldb_robber:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: 'mysqldb'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_USER: yang
      MYSQL_DATABASE: robber_db

  mysqldb_house:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: 'mysqldb'
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_USER: yang
      MYSQL_DATABASE: house_db

  adminer:
    image: adminer
    hostname: 'adminer'
    restart: always
    ports:
      - 8090:8090

networks:
  broker-kafka:
    driver: bridge